version: '3.8'

services:
  web:
    container_name: mowz-auth-web
    build:
      context: .
      dockerfile: deployments/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go server
    networks:
      - mowz-net
  database:
    build:
      context: .
      dockerfile: deployments/db.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 540220.Amir
      MYSQL_USER: mowz_db
      MYSQL_PASSWORD: 540220.Amir
      MYSQL_DATABASE: mowz
    container_name: mowz-auth-db
    ports:
      - "3307:3306"
    volumes:
      - mowz-auth-db:/var/lib/mysql
    networks:
      - mowz-net


  prometheus:
    image: prom/prometheus
    volumes:
      - ./deployments/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - mowz-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - mowz-net

volumes:
  mowz-auth-db:
networks:
  mowz-net:
    driver: bridge